[versions]
agp = "8.9.2"
kotlin = "2.1.20"
collektive = "24.0.0"
coreKtx = "1.16.0"
hivemq = "1.3.5"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin-logging = "7.0.7"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
serialization = "1.8.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
ble = { module = "no.nordicsemi.android:ble", version = "2.10.0" }
ble-ktx = { module = "no.nordicsemi.android:ble-ktx", version = "2.10.0" }
collektive = { module = "it.unibo.collektive:collektive-dsl", version.ref = "collektive" }
collektive-stdlib = { module = "it.unibo.collektive:collektive-stdlib", version.ref = "collektive" }
collektive-plugin = { module = "it.unibo.collektive:collektive-compiler-plugin", version.ref = "collektive" }
hivemq = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq" }
hivemq-reactor = { module = "com.hivemq:hivemq-mqtt-client-reactor", version.ref = "hivemq" }
kotlin-logging-android = { module = "io.github.oshai:kotlin-logging-android", version.ref = "kotlin-logging" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.2"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
mesh = { module = "no.nordicsemi.android:mesh", version = "3.3.4" }
mktt = { module = "it.nicolasfarabegoli:mktt", version = "1.2.3" }
slf4j = "org.slf4j:slf4j-api:2.0.17"

[bundles]
collektive = [ "collektive", "collektive-stdlib", "collektive-plugin" ]
hivemq = ["hivemq", "hivemq-reactor"]
serialization = [ "kotlinx-serialization-json", "kotlinx-serialization-protobuf" ]
logging = [ "kotlin-logging-android", "slf4j" ]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
collektive = { id = "it.unibo.collektive.collektive-plugin", version.ref = "collektive" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.86.1"
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
taskTree = "com.dorongold.task-tree:4.0.1"

