
name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Check the simulations on CI
        uses: DanySK/build-check-deploy-gradle-action@4.0.9
        with:
          deploy-command: true
          should-run-codecov: false
          should-validate-wrapper: ${{ contains('Linux', runner.os) }}
  success:
    runs-on: ubuntu-latest
    needs:
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
